CREATE DATABASE IF NOT EXISTS Pelan;

CREATE TABLE IF NOT EXISTS teams (
    ID INT NOT NULL AUTO_INCREMENT,
    InsertDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Title VARCHAR(45) NOT NULL,
    Abbreviation VARCHAR(4) NOT NULL,
    Public Boolean,
    UNIQUE INDEX `UNIQUE_Title` (`Title`),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS roles (
    ID INT NOT NULL AUTO_INCREMENT,
    InsertDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Title VARCHAR(45) NOT NULL,
    Abbreviation VARCHAR(4) NOT NULL,
    Admin Boolean NOT NULL,
    Teams_ID INT NOT NULL,
    UNIQUE INDEX `UNIQUE_Title_per_Team` (`Title`, `Teams_ID`),
    UNIQUE INDEX `UNIQUE_Abbreviation_per_Team` (`Abbreviation`, `Teams_ID`),
    PRIMARY KEY (ID),
    FOREIGN KEY (Teams_ID) REFERENCES teams(ID)
);

CREATE TABLE IF NOT EXISTS users (
    ID INT NOT NULL AUTO_INCREMENT,
    InsertDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	Firstname VARCHAR(45) NOT NULL,
	Lastname VARCHAR(45) NOT NULL,
    Language VARCHAR(2) NOT NULL,
    Identifier TEXT NOT NULL,
    Nickname VARCHAR(6) NOT NULL,
	Email VARCHAR(45) NOT NULL,
    Roles_ID INT,
    Teams_ID INT,
    UNIQUE INDEX `UNIQUE_Email` (`Email`),
    UNIQUE INDEX `UNIQUE_Nickname_per_Team` (`Nickname`, `Teams_ID`),
    PRIMARY KEY (ID),
	FOREIGN KEY (Roles_ID) REFERENCES roles(ID),
	FOREIGN KEY (Teams_ID) REFERENCES teams(ID)
);

CREATE TABLE IF NOT EXISTS shifts (
    ID INT NOT NULL AUTO_INCREMENT,
    InsertDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Title VARCHAR(45) NOT NULL,
    Abbreviation VARCHAR(4) NOT NULL,
	Color VARCHAR(45) NOT NULL,
    Description VARCHAR(45),
    Teams_ID INT NOT NULL,
    UNIQUE INDEX `UNIQUE_Title_per_Team` (`Title`, `Teams_ID`),
    UNIQUE INDEX `UNIQUE_Abbreviation_per_Team` (`Abbreviation`, `Teams_ID`),
    PRIMARY KEY (ID),
	FOREIGN KEY (Teams_ID) REFERENCES teams(ID)
);

CREATE TABLE IF NOT EXISTS times (
    ID INT NOT NULL AUTO_INCREMENT,
    InsertDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Description VARCHAR(45),
    Title VARCHAR(45) NOT NULL,
    Abbreviation VARCHAR(4) NOT NULL,
    Position INT NOT NULL,
	Teams_ID INT NOT NULL,
    UNIQUE INDEX `UNIQUE_Title_per_Team` (`Title`, `Teams_ID`),
    UNIQUE INDEX `UNIQUE_Abbreviation_per_Team` (`Abbreviation`, `Teams_ID`),
    UNIQUE INDEX `UNIQUE_Position_per_Team` (`Position`, `Teams_ID`),
    PRIMARY KEY (ID),
	FOREIGN KEY (Teams_ID) REFERENCES teams(ID)
);

CREATE TABLE IF NOT EXISTS assignments (
    ID INT NOT NULL AUTO_INCREMENT,
    InsertDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Note VARCHAR(45),
    Date DATE NOT NULL,
	Times_ID INT NOT NULL,
	Shifts_ID INT NOT NULL,
	Users_ID INT NOT NULL,
    UNIQUE INDEX `UNIQUE_Time_per_User_and_Shift_per_Date` (`Times_ID`, `Users_ID`, `Shifts_ID`, `Date`),
    PRIMARY KEY (ID),
	FOREIGN KEY (Times_ID) REFERENCES times(ID),
	FOREIGN KEY (Shifts_ID) REFERENCES shifts(ID),
	FOREIGN KEY (Users_ID) REFERENCES users(ID)
);
